Windows installer creation

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -32,12 +32,8 @@ WIN32_PIDGIN_SRC_DIR=win32/pidgin-${PIDGIN_VERSION}
 WIN32_PIDGIN_BIN_URL=http://sourceforge.net/projects/pidgin/files/Pidgin/${PIDGIN_VERSION}/pidgin-${PIDGIN_VERSION}-win32-bin.zip/download
 WIN32_PIDGIN_BIN_FILE=win32/pidgin-${PIDGIN_VERSION}-win32-bin.zip
 WIN32_PIDGIN_BIN_DIR=win32/pidgin-${PIDGIN_VERSION}-win32bin
-WIN32_WEBP_URL=http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-0.6.0.tar.gz
-WIN32_WEBP_FILE=win32/libwebp-0.6.0.tar.gz
-WIN32_WEBP_DIR=win32/libwebp-0.6.0
-WIN32_DIRS=${WIN32_GTK_BUNDLE_DIR} ${WIN32_PIDGIN_SRC_DIR} ${WIN32_PIDGIN_BIN_DIR} ${WIN32_WEBP_DIR}
+WIN32_DIRS=${WIN32_GTK_BUNDLE_DIR} ${WIN32_PIDGIN_SRC_DIR} ${WIN32_PIDGIN_BIN_DIR}
 # Not directly used here, but the usage will be injected via the CFLAGS configure var.
-# Note to webp: locally cross-built!  That's why it violates the pattern.
 WIN32_INC=-I${WIN32_PIDGIN_SRC_DIR}/pidgin \
           -I${WIN32_PIDGIN_SRC_DIR}/pidgin/win32 \
           -I${WIN32_PIDGIN_SRC_DIR}/libpurple \
@@ -46,8 +42,8 @@ WIN32_INC=-I${WIN32_PIDGIN_SRC_DIR}/pidgin \
           -I${WIN32_GTK_BUNDLE_DIR}/include/glib-2.0 \
           -I${WIN32_GTK_BUNDLE_DIR}/lib/glib-2.0/include \
           -I${WIN32_GTK_BUNDLE_DIR}/include/gtk-2.0 \
-          -I${WIN32_GTK_BUNDLE_DIR}/lib/gtk-2.0/include \
-          -Iobjs/webp/include
+          -I${WIN32_GTK_BUNDLE_DIR}/lib/gtk-2.0/include
+WIN32_CONTRIB_FILES=contrib/libgcrypt-20.dll contrib/libgpg-error-0.dll contrib/libgcc_s_sjlj-1.dll
 
 CFLAGS_INTL=-DENABLE_NLS -DLOCALEDIR='"$(localedir)"'
 CFLAGS_WARN=-Wall -Wextra -Wno-deprecated-declarations -Wno-unused-parameter
@@ -73,7 +69,7 @@ endif
 DEP=dep
 EXE=bin
 OBJ=objs
-DIR_LIST=${DEP} ${EXE} ${OBJ}
+DIR_LIST=${DEP} ${EXE} ${OBJ} contrib
 
 PLUGIN_OBJECTS=${OBJ}/tgp-net.o ${OBJ}/tgp-timers.o ${OBJ}/msglog.o ${OBJ}/telegram-base.o ${OBJ}/telegram-purple.o ${OBJ}/tgp-2prpl.o ${OBJ}/tgp-structs.o ${OBJ}/tgp-utils.o ${OBJ}/tgp-chat.o ${OBJ}/tgp-ft.o ${OBJ}/tgp-msg.o ${OBJ}/tgp-request.o ${OBJ}/tgp-blist.o ${OBJ}/tgp-info.o
 ALL_OBJS=${PLUGIN_OBJECTS}
@@ -233,11 +229,29 @@ ${WIN32_PIDGIN_BIN_DIR}: | ${WIN32_PIDGIN_BIN_FILE}
 ${WIN32_PIDGIN_BIN_FILE}: | win32
 	wget -q -O $@ ${WIN32_PIDGIN_BIN_URL}
 
-${WIN32_WEBP_DIR}: | ${WIN32_WEBP_FILE}
-	tar xf $| -C win32/
+.PHONY: win-installer-deps
+win-installer-deps: telegram-purple.nsi $(PRPL_LIBNAME) $(LOCALE_MOS) ${WIN32_CONTRIB_FILES}
+	@[ "x${PRPL_NAME}" = "xlibtelegram.dll" ] || { \
+		echo "WARNING: Bad PRPL_NAME.  This probably won't work." ; \
+		echo "         (The DLL file cannot be just renamed!)" ; }
 
-${WIN32_WEBP_FILE}: | win32
-	wget -q -O $@ ${WIN32_WEBP_URL}
+/usr/%:
+	@echo "You're missing the file $@"
+	@echo "Try installing the appropriate of the following packages:"
+	@echo "    libgcrypt-mingw-w64-dev"
+	@echo "    libgpg-error-mingw-w64-dev"
+	@echo "    gcc-mingw-w64-i686"
+	@echo "Also, please file a bug report *EVEN IF THIS SOLVES THE ISSUE*,"
+	@echo "as it should have been detected earlier."
+
+contrib/libgcrypt-20.dll: /usr/i686-w64-mingw32/bin/libgcrypt-20.dll | contrib
+	cp $< "$@"
+
+contrib/libgpg-error-0.dll: /usr/i686-w64-mingw32/bin/libgpg-error-0.dll | contrib
+	cp $< "$@"
+
+contrib/libgcc_s_sjlj-1.dll: /usr/lib/gcc/i686-w64-mingw32/*-win32/libgcc_s_sjlj-1.dll | contrib
+	cp $< "$@"
 
 
 ### == Handling and maintenance. Subject to rapid change, shouldn't be used in scripts. == ###
